Foxy/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth.urls')),
    path('',include('Social.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Social/urls.py
from django.urls import path
from Social import views

urlpatterns = [
    path('', views.wall.as_view()),
    path('post/',views.Post.as_view()),
    path('home/', views.Home.as_view()),
    path('post/<int:pk>/like', views.PostLike.as_view()),
    path('post/<int:pk>/comment', views.PostComment.as_view())
]

auth/urls.py
from django.urls import path
from auth import views

urlpatterns = [
    path('login/', views.Login.as_view()),
    path('logout/', views.Logout.as_view()),
    path('signup/', views.Signup.as_view())
]

Social/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    content = models.TextField()
    image = models.ImageField(blank = True)
    
    def __str__(self): return self.content[:15]
    
class Like(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Comment(models.Model):
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length = 1024)

class Friends(models.Model):
    person1=models.ForeignKey(User,on_delete=models.CASCADE,related_name='person1')
    person2=models.ForeignKey(User,on_delete=models.CASCADE,related_name='person2')
    
    

Social/forms.py
from django import forms
from Social import models

class PostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['content', 'image']

class PostComment(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['content']  

Social/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import SingleObjectMixin
from django.db.models import Q
from django.views import View
from Social import models,forms


# Create your views here.
class wall(LoginRequiredMixin,ListView):
    context_object_name = 'posts'
    template_name = 'Social/wall.html'
    login_url = 'auth/login'

    def get_queryset(self):
        friendsIds = [friend.person2.id for friend in models.Friends.objects.filter(person1 = self.request.user)]
        friendsIds+= [friend.person1.id for friend in models.Friends.objects.filter(person2 = self.request.user)]
        return models.Post.objects.filter(user__in = friendsIds).order_by('-created_at')
        
        # return models.Post.objects.filter(
        #     (Q(user__person1=self.request.user.pk) | Q(user__person2=self.request.user.pk)) &
        #     ~Q(user = self.request.user)
        # ).order_by('-created_at')


class Home(LoginRequiredMixin, ListView):
    context_object_name = 'posts'
    template_name = 'Social/home.html'
    login_url = 'auth/login'

    def get_queryset(self):
        return models.Post.objects.filter(Q(user=self.request.user)).order_by('-created_at')

    def get_context_data(self, *args, **kwargs):
        data = super().get_context_data(*args, **kwargs)
        data['post_form'] = forms.PostForm()
        return data

class Post(View):
    def post(self, request):
        form = forms.PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

        return redirect('/home/')


class PostLike(View):
    model = models.Post

    def post(self, request, pk):
        post =self.model.objects.get(pk=pk)
        models.Like.objects.create(post=self.object, user=request.user)
        return HttpResponse(code=204)
        
class PostComment(View):
    model = models.Post
    form = forms.PostComment
    def post(self, request, pk):
        post = self.model.objects.get(pk=pk)
        form = self.form(request.POST)
        if form.is_valid():
            comment=form.save(commite=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return HttpResponse(code=204)
        return HttpResponse("Error")
        

templates/Social/components/post.html
<div class="card">
    <div class="card-image">
        {% if post.image %}
            <img src="/media/{{ post.image }}" style="width:25%">
        {% endif %}
    </div>
    <div class="card-content">
      <span class="card-title"> {{ post.user.first_name }}  {{ post.user.last_name }}</span>
      <span>{{ post.created_at }}</span>
      <p> {{ post.content }}</p>
    </div>
    <div class="card-action">
        <a href="#" onclick="likePost({{post.id}})">{{ post.like_set.count }} Likes</a>
        <a class="modal-trigger" href="#postModal{{post.id}}">{{ post.comment_set.count }} Comments</a>
    </div>
   </div>

    <div id="postModal{{post.id}}" class="modal">
        <div class="modal-content">
          <h4>Comments</h4>
          <ul>
            {% for comment in post.comment_set.all %}
            <li>{{comment.user.first_name}}-{{comment.content}}</li>
            {% endfor %}
          </ul>
          <form onsubmit="commentPost({{post.id}}, document.getElementById('comment{{post.id}}').value);">
            <div class="input-field">
              <input id="comment{{post.id}}" type="text" class="validate">
              <label for="comment{{post.id}}">Comment</label>
              <button type="submit" class="btn waves-effect">Submit</button>
            </div>
          </form>

        </div>
    </div>

templates/Social/home.html
{% extends 'auth\base.html' %}
{% block content %}

  
<div class="container">
  <h4>Home</h4>
  <form action="/post/" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ post_form }}

    <button class="waves-effect waves-light btn"  type="submit">POST</button>
  </form>
  
  {% for post in posts %}
  <div class="row">
    <div class="col s12">
      {% include 'Social/components/post.html' %}
    </div>
  </div>
  {% endfor %}
</div>
  
{% endblock %}

templates/Social/wall.html
{% extends 'auth\base.html' %}

{% block content %}
<div class="container">
  <h4>News Feed</h4>
  {% for post in posts %}
  <div class="row">
    <div class="col s12">
        {% include 'Social/components/post.html' %}
      

    </div>
  </div>
{% endfor %}

</div>

{% endblock %}